spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usersdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  application:
    name: user-service

server:
  port: 8081
