spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/usersdb
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  application:
    name: user-service
